export const MODEL_PATHS = {
  earth: {
    hqTree: "/models/hq/island_tree_02.glb",
    hqFern: "/models/hq/fern_02.glb",
    hqBoulder: "/models/hq/boulder_01.glb",
    hqTreeStump: "/models/hq/tree_stump_01.glb",
    hqMoss: "/models/hq/moss_01.glb",
    hqGrassMedium01: "/models/hq/grass_medium_01.glb",
    fantasyHouse: "/models/medieval_village_pack/fantasy_house_02.glb",
    fantasyInn: "/models/medieval_village_pack/fantasy_inn.glb",
    townHouse: "/models/medieval_village_pack/fantasy_house_03.glb",
    towerHouse: "/models/medieval_village_pack/bell_tower.glb",
    bigBuilding: "/models/medieval_village_pack/fantasy_barracks.glb",
    cypressTree: "/models/fantasy_village/cypress_tree.glb",
    flowers: "/models/fantasy_village/flowers.glb",
    flowerBushes: "/models/fantasy_village/flower_bushes.glb",

    bellTower: "/models/medieval_village_pack/bell_tower.glb",
    mill: "/models/medieval_village_pack/mill.glb",
    blacksmith: "/models/medieval_village_pack/blacksmith.glb",
    barracks: "/models/medieval_village_pack/fantasy_barracks.glb",
    sawmill: "/models/medieval_village_pack/fantasy_sawmill.glb",
    stable: "/models/medieval_village_pack/fantasy_stable.glb",

    house01: "/models/medieval_village_pack/fantasy_house_01.glb",
    house02: "/models/medieval_village_pack/fantasy_house_02.glb",
    house03: "/models/medieval_village_pack/fantasy_house_03.glb",

    marketStand01: "/models/medieval_village_pack/market_stand_01.glb",
    marketStand02: "/models/medieval_village_pack/market_stand_02.glb",
    well: "/models/medieval_village_pack/well.glb",
    cart: "/models/medieval_village_pack/cart.glb",
    barrel: "/models/medieval_village_pack/barrel.glb",
    crate: "/models/medieval_village_pack/crate.glb",
    fence: "/models/medieval_village_pack/fence.glb",
    polypizzaGrass01: "/models/polypizza/grass_quaternius.glb",
    polypizzaGrass02: "/models/polypizza/grass_quaternius_2.glb",
    polypizzaPathRoundWide: "/models/polypizza/rock_path_round_wide.glb",
    polypizzaPathSquareSmall: "/models/polypizza/rock_path_square_small.glb",
  }
}
